pages:
  image: node:20
  script:
    - npm install
    - VITE_BASE_URL=/reyohoho/ npm run build
    - rm -rf ./public
    - mkdir ./public
    - cp -r ./dist/* ./public/
  artifacts:
    paths:
      - public
  only:
    - vue
